### ISSUE TITLE
User can see their car 

### ISSUE THREAD

**Issue by udaibirv** [udaibirv/driving-game#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x]  Set background color of page

- [x] Get image of car 

- [x] Make sure image of the car is on the top left of the screen

- [x] Make sure the size of the car is not too big
