### ISSUE TITLE
User can turn their car 

### ISSUE THREAD

**Issue by udaibirv** [udaibirv/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Listen for keydown events on the car 

- [x] Change theClassName of the car image whenever the user presses an arrow key up, left, down, right

- [x] Utilize transform css property to change car in the direction the user presses the key for
